/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a car_adaptor car.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "car_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CarAdaptor
 */

CarAdaptor::CarAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CarAdaptor::~CarAdaptor()
{
    // destructor
}

int CarAdaptor::speed() const
{
    // get the value of property speed
    return qvariant_cast< int >(parent()->property("speed"));
}

double CarAdaptor::getBattery()
{
    // handle method call local.Car.getBattery
    double out0;
    QMetaObject::invokeMethod(parent(), "getBattery", Q_RETURN_ARG(double, out0));
    return out0;
}

double CarAdaptor::getSpeed()
{
    // handle method call local.Car.getSpeed
    double out0;
    QMetaObject::invokeMethod(parent(), "getSpeed", Q_RETURN_ARG(double, out0));
    return out0;
}

void CarAdaptor::setBattery(double battery)
{
    // handle method call local.Car.setBattery
    QMetaObject::invokeMethod(parent(), "setBattery", Q_ARG(double, battery));
}

void CarAdaptor::setSpeed(double speed)
{
    // handle method call local.Car.setSpeed
    QMetaObject::invokeMethod(parent(), "setSpeed", Q_ARG(double, speed));
}

