/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a car_adaptor car.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "car_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CarAdaptor
 */

CarAdaptor::CarAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CarAdaptor::~CarAdaptor()
{
    // destructor
}

void CarAdaptor::setBattery(int battery)
{
    // handle method call local.Car.setBattery
    QMetaObject::invokeMethod(parent(), "setBattery", Q_ARG(int, battery));
}

void CarAdaptor::setRPM(int rpm)
{
    // handle method call local.Car.setRPM
    QMetaObject::invokeMethod(parent(), "setRPM", Q_ARG(int, rpm));
}

void CarAdaptor::setSpeed(int speed)
{
    // handle method call local.Car.setSpeed
    QMetaObject::invokeMethod(parent(), "setSpeed", Q_ARG(int, speed));
}

